title: ""
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: sergey.dukhovich
github_username:  SergeyDukhovich
minimal_mistakes_skin: air
search: true

locale: ru

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/
paginate: 10
paginate_path: /page:num/
timezone: "Europe/Minsk" 

words_per_minute: 200
comments:
  provider: "disqus"
  disqus:
    shortname: "dukhovich"

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Sergey Dukhovich"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Software Developer"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sergeydukhovich"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/sergey-dukhovich/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/sergeydukhovich/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/sergey.dukhovich/"
    - label: "Goodreads"
      icon: "fab fa-fw fa-goodreads"
      url: "https://www.goodreads.com/sergeydukhovich"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true