title: "Сергей Духович"
description: >-
  Статьи по RxSwift, автор Сергей Духович.
twitter_username: sergey.dukhovich
github_username:  SergeyDukhovich
minimal_mistakes_skin: air
search: true
search_full_content: true

analytics:
  provider: custom
yandex_site_verification: "69e839831ef6cfd8"

locale: ru
link_to_translated_base: http://dukhovich.net

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/
paginate: 10
paginate_path: /page:num/
timezone: "Europe/Minsk" 

words_per_minute: 200
comments:
  provider: "disqus"
  disqus:
    shortname: "dukhovichby"

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Sergey Dukhovich"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Software Developer"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sergeydukhovich"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/sergey-dukhovich/"
    - label: "Resume"
      icon: "fas fa-fw fa-file-word"
      url: "http://dukhovich.by/assets/ru_dukhovich_sergey_cv_ios.docx"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true